### PR TITLE
Download files

### PR DESCRIPTION
**Pull request by Topvennie**
Added the ability to download submission and log files.

`/api/submissions/<id>/zip/` to download the submission zip file.
`/api/extra-check-results/<id>/log/` to download the log file.

### CODE REVIEW

**Review by DeLany123 — CHANGES_REQUESTED** [review]
links to submissions from group or project don't work now. This needs to be fixed first (:

**Review by DeLany123 — CHANGES_REQUESTED** [review]
The project type has still a non-working submissions url.
https://localhost/api/projects/0/submissions/

**Comment by Topvennie** [comment]
Polymorphic types being annoying again, can you try again?

**Review by DeLany123 — APPROVED** [review]
I don't know how to write emoji's..

**Pull request merged**
